id: PE58C77F1
initial_creation_type: input
source_metadata:
  title: Vajrakīla Series
  language: en
  description: 'A series of texts related to the deity Vajrakīla or Vajrakīlaya (rdo
    rje phur ba):'
  volume:
    a861247dd56b4532976721a557a52f73:
      title: A Short Practice for Averting Obstacles through Vajrakīla
      parent: Averting Obstacles
    41e4da3d803344eca5c8d6e569ce4d8c:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Commentaries
    d866b3a52b3a412db87aa6bb706127cf:
      title: 'Offering Clouds of Samantabhadra: Confession and Fulfilment'
      parent: Confession and Fulfilment
    7bf47982f05e4ad7b9d937207cea8985:
      title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for
        the ''Neck-Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Fire Offering
    ef3a8f3ddf54436988a05245ac8a2de2:
      title: 'Inventory: The Perfectly Clear Mirror from the Razor of the Innermost
        Essence'
      parent: Inventories
    f39b77af08014e149f0b6ead771b6d71:
      title: 'The Swift Infusion of Blessings: A Lineage Prayer for the Single Mind
        Kīla Heart-Practice, Part of the ''Neck Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Lineage Prayers
    1dd0cd6ba7b6490ea80fdfd8f05bd87d:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Lineage Prayers
    2d8bf595b1904971b944ded773e704d3:
      title: A Vajrakīla Lineage Prayer
      parent: Lineage Prayers
    4aee93d9f2a24a1fb04055ca251d22a1:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Offering
    0f9faf36749d4f44b715452b5ef22451:
      title: The Eight-Branch Offering from the Gyüluk Phurba
      parent: Offering
    035aa6a855da4fe1811529769bbcee6c:
      title: Invocation of the Vidyādhara Gurus
      parent: Prayers
    52a73cba0d2a41d9b96a7397a5ee83f1:
      title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
      parent: Prayers
    d7c2f84bebe648468c9b918cfa9b46ed:
      title: The Summoning of Blessings which Brings them Swift and Fast
      parent: Prayers
    26725cc2c59c4661968cfdb6ff9388fa:
      title: Entrusting Activity
      parent: Protectors
    92ec40a068f6406faf625e31c1f7784c:
      title: Offering to the Dharma Guardians of the 'Neck-Pouch Dagger’ (Purba Gulkhukma)
        Cycle
      parent: Protectors
    1ffed0dd96954b30a81cf271ddaac57d:
      title: Daily Practice of Vajrakīla
      parent: Sādhanas
    1cfd9bba7a3b4d2fa4b4517586db79b5:
      title: The Essential Daily Practice of Vajrakīla
      parent: Sādhanas
    bf4898266cc74b99bec2a36c2390c2da:
      title: 'The Accomplishment of Supreme Enlightened Activity: A Recitation Manual
        for The Vajrakīla Root Tantra Section'
      parent: Sādhanas
    69150024655a4287b9460c76f42587ea:
      title: 'Inlaid Jewels: Addenda to the ''Neck-Pouch Dagger’ (Purba Gulkhukma)
        Cycle'
      parent: Sādhanas
    8077f71ca4664fd8821679622ab7d5d7:
      title: The Single Mind Kīla Practice, Part of the 'Neck-Pouch Dagger’ (Purba
        Gulkhukma) Cycle
      parent: Sādhanas
    82910398b946473f9cba271eea454881:
      title: The Wisdom Mind Practice of One Kīla
      parent: Sādhanas
    23f4d3b7ed5b4220b2cea140acaf71f1:
      title: A Section of the Vajrakīla Root Tantra
      parent: Tantras
created_at: '2022-03-01T06:29:47.476864'
last_modified_at: '2022-03-01T06:29:47.476871'
